name: Deploy to Yandex Cloud

on:
  push:
    branches: [ main, master ]  # срабатывает при пуше в эти ветки

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd ~/Parser/jobpulse &&
            git pull origin main &&
            docker compose up -d --build --force-recreate
          "